name: Release

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to release from (e.g. `refs/tags/v1.2.3`)'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Create GitHub Release
        uses: taiki-e/create-gh-release-action@v1
        with:
          # must be a full ref (refs/tags/… or refs/heads/…)
          ref: ${{ github.event.inputs.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          # optional overrides:
          draft: false
          allow-missing-changelog: true

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build & upload binaries
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: liveu_stats_bot
          tar: unix
          zip: windows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_PROFILE_RELEASE_LTO: true
