name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag name to release (e.g. v1.2.3)'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Create GitHub Release
        uses: taiki-e/create-gh-release-action@v1
        with:
          tag: ${{ github.event.inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build & upload binaries
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: liveu_stats_bot
          tar: unix
          zip: windows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_PROFILE_RELEASE_LTO: true
